import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - CommentFlow",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-[#0f172a]" style={{ fontFamily: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif" }}>
      <nav className="sticky top-0 z-50 bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-2.5 font-extrabold text-lg tracking-tight">
            <div className="w-8 h-8 bg-[#0d6efd] rounded-lg flex items-center justify-center text-white text-sm font-bold">CF</div>
            Comment<span className="text-[#0d6efd]">Flow</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-extrabold mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: February 2025</p>

        <div className="prose prose-gray max-w-none space-y-8 text-[15px] leading-relaxed text-gray-600">
          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using CommentFlow (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">2. Description of Service</h2>
            <p>CommentFlow is an AI-powered comment marketing platform that helps users discover relevant social media posts, generate AI-powered comments, and manage their posting through a Chrome extension. The Service includes a web dashboard, AI comment generation, post discovery, and a browser extension.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">3. Account Registration</h2>
            <p>To use the Service, you must create an account with a valid email address and password. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">4. Acceptable Use</h2>
            <p>You agree to use the Service in compliance with all applicable laws and the terms of service of third-party platforms (including Reddit and YouTube). You agree NOT to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service to generate spam, misleading, or deceptive content</li>
              <li>Violate the terms of service of Reddit, YouTube, or any other platform</li>
              <li>Use the Service for harassment, abuse, or illegal purposes</li>
              <li>Attempt to circumvent platform rules or detection mechanisms in ways that violate their terms</li>
              <li>Share your account credentials or extension token with unauthorized parties</li>
              <li>Use the Service to impersonate other individuals or entities</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">5. AI-Generated Content</h2>
            <p>Comments generated by the Service are created using artificial intelligence (OpenAI). While we strive to produce high-quality, natural-sounding content, you are solely responsible for reviewing and approving all AI-generated comments before they are posted. CommentFlow is not liable for any consequences arising from the content of comments posted through the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">6. Chrome Extension</h2>
            <p>The CommentFlow Chrome extension operates within your browser and uses your existing social media sessions to post comments. By using the extension, you acknowledge that:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Comments are posted from your personal accounts</li>
              <li>You are responsible for the content posted through the extension</li>
              <li>Platform-specific consequences (account warnings, bans) are your responsibility</li>
              <li>The extension requires certain browser permissions to function</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">7. Subscription and Payment</h2>
            <p>Certain features of the Service require a paid subscription. By subscribing, you agree to pay the applicable fees. Subscriptions renew automatically unless cancelled before the renewal date. Refunds are handled on a case-by-case basis. We reserve the right to change pricing with 30 days notice.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, CommentFlow and its team shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising out of or in connection with your use of the Service.</p>
            <p>CommentFlow is not responsible for any actions taken by third-party platforms (such as Reddit or YouTube) against your accounts as a result of using the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">9. Disclaimer of Warranties</h2>
            <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. We do not guarantee that the Service will be uninterrupted, error-free, or that AI-generated content will meet your specific requirements.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">10. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our sole discretion. Upon termination, your right to use the Service will immediately cease. You may also terminate your account at any time by contacting us.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">11. Changes to Terms</h2>
            <p>We may modify these Terms of Service at any time. We will notify you of material changes by email or through a notice on our website. Your continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0f172a] mb-3">12. Contact</h2>
            <p>If you have questions about these Terms of Service, contact us at <strong>support@commentflow.io</strong>.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
